version: "3.7"
services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_DB: ${APP_DATABASE_NAME}
    ports:
      - "5432:5432"
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
